# Site settings
name: Welcome
email: zhtoooooo@163.com
author: 张桐
url: https://www.zhangto.github.io
resume_site: https://www.zhangto.github.io
github: https://github.com/zhangto
baseurl: ""
description: Hello World
meta_description: 个人博客
motto: 面朝大海，春暖花开
banner: 你说你孤独，就像很久以前，火星照耀十三个州府。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zhangto

# Build settings
markdown: kramdown
